// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttafppumxziwsncfldss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0YWZwcHVteHppd3NuY2ZsZHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzgxMzksImV4cCI6MjA2MTA1NDEzOX0.nkvzxbJ6QL6pVELYACHxWHrhfZH-Ij2LkfQicrf3rk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);